apiVersion: v2
name: cdash
description: A Helm chart for Kubernetes
type: application
version: "0.1.0"
appVersion: "3.4.1"
dependencies:
  - name: postgresql
    version: "15.5.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: global.postgresql.enabled
  - name: minio
    version: "14.6.2"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: global.minio.enabled
