website:
  resources:
    limits:
      memory: 256Mi

worker:
  resources:
    limits:
      memory: 256Mi

# See here for more config settings: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
postgresql:
  enabled: true
  auth:
    database: cdash

global:
  cdash:
    image: kitware/cdash:latest

  postgresql:
    auth:
      postgresPassword: test
